### ISSUE TITLE
Centrare giorno selezionato quando si apre il pannello timesheets

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#100]
Quando si fa doppio click su un giorno posizonato in basso, all'apertura del pannello di inserimento dei timesheets, questo viene coperto confondendo l'utente.
Quando si apre il pannello, visualizzare il giorno selezionato nella parte superiore in maniera che sia sempre sott'occhio

**Comment by corradinia91** [comment]
Con i metodi di default si può solo portare il giorno nella zona di tabella visibile. Può bastare?
