### ISSUE TITLE
Note cantiere

### ISSUE THREAD

**Issue by corradinia91** [bacca87/great2#101]
Le note cantiere non devono essere visualizzate nella colonna factory dei timesheet. 
Valutare dove visualizzarle

**Comment by bacca87** [comment]
Ho un paio di idee:

1.  Mettere un iconcina sul giorno che se cliccata o al passaggio del mouse apre un tooltip con i commenti.
2.  Aggiungere una colonna note limitata a un numero massimo di caratteri troncati da "...", e al passaggio del mouse mostra il testo completo in un tooltip. (es. "In cantiere ho sco..." )

**Comment by masierim** [comment]
la due

**Comment by masierim** [comment]
io ci sto scrivendo più o meno così : COPLIN | CC1366 F2ZZ004
