### ISSUE TITLE
salvataggio dati time sheets page

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#103]
non so se è già stata aperta una segnalazione per questo... in ogni modo...

nel riquadro EDIT se cambio FDL o NOTE viene salvato senza bisogno di premere SAVE...

**Comment by corradinia91** [comment]
Secondo me si riferisce all'sìissue #39. Puoi verificare che anche dopo il riavvio i dati siano salvati senza premere save?

**Comment by masierim** [comment]
si.

**Comment by masierim** [comment]
se non premo save, dopo il riavvio vengono ripristinati i dati originali

**Comment by bacca87** [comment]
si è relativo all'issue #39

**Comment by bacca87** [comment]
questo problema sembra esserci ovunque ci sia una selezione a combobox, quindi anche nella selezione delle factories associate al FDL, per esempio.

**Comment by bacca87** [comment]
per i timesheets è stato risolto, ora mancano gli altri combo
