### ISSUE TITLE
note in time sheets

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#104]
Perchè non posso inserire delle note su giorni che non ci sono ore o FDL associato?

**Comment by bacca87** [comment]
ottima domanda!

**Comment by masierim** [comment]
> ottima domanda!

lo so,io faccio solo ottime domande.... XD

**Comment by corradinia91** [comment]
Quando ho messo il campo note non pensavo avesse senso aggiungerle per un giorno non lavorato. Le note sono legate al timesheet, che non può esistere senza orari. Serve legare le note al giorno anzichè i timesheet?

**Comment by bacca87** [comment]
Attenzione peró, i timesheet vuoti senza FDL no!

**Comment by corradinia91** [comment]
Secondo me lui sta aggiungendo timesheet senza fdl

**Comment by corradinia91** [comment]
Le note sono legate al timesheet, perchè io posso poter mettere una nota per ogni lavoro giornaliero che faccio. Pertanto le note le puoi usare nei seguenti casi:
1) Timesheet classico con inizio/fine lavoro
2) Timesheet vuoto con FDL associato
Che utilità ti da poter mettere delle note per un giorno senza timesheet/fdl?

**Comment by masierim** [comment]
> Che utilità ti da poter mettere delle note per un giorno senza timesheet/fdl?

per esempio se io so che fra due settimane dovrò lavorare per pincopallino. intanto ci metto "pincopallino" poi metterò le ore...

**Comment by bacca87** [comment]
Io valuterei di associare le note al giorno invece che al timesheet.
Tanto anche se lavori su 2 impianti diversi va bene lo stesso, le note sono un testo aperto.

**Comment by corradinia91** [comment]
Io invece le note del ts le uso per metterci la wbs.. cos' ho sia le ore lavorate che l'ordine. A me tornano comode nel ts. Allora aggiungiamo anche quelle del giorno

**Comment by bacca87** [comment]
la wbs la puoi mettere anche nelle note del giorno. 
tu inserisci un timesheet per wbs? tipo lavori su 3 wbs e metti 3 timesheets?

**Comment by corradinia91** [comment]
es: io lavoro 3 ore per h24. metto un ts di 3 ore con wbs h24. 
Questo torna comodo quando imputi su sap che devi distinguere le ore lavorate per ogni wbs

Potremmo rinominare le note attuali del ts come "Ordine" e poi mettere il campo note del giorno

**Comment by bacca87** [comment]
un alternativa, che ci viene quasi gratis, potrebbe essere quella di permettere l'inserimento dei timesheet vuoti solo se hanno almeno un FDL o una Nota.

**Comment by corradinia91** [comment]
Stavo per proporlo

**Comment by bacca87** [comment]
ok dai, procediamo cosi...
