### ISSUE TITLE
Problema salvataggio coordinate manuali stabilimento

### ISSUE THREAD

**Issue by BoniniJ** [bacca87/great2#105]
Una volta settate le coordinate manualmente di uno stabilimento dopo aver cliccato il pulsante salva esce l'errore in allegato.

![image](https://user-images.githubusercontent.com/54804322/64113122-bad14000-cd89-11e9-8cc3-e1aad3d0947f.png)

**Comment by corradinia91** [comment]
Io ho provato con uno stabilimento esistente e non ho il tuo errore. Hai creato un nuovo stabilimento? In entrambi i casi dovresti vedere i campi con errore
![immagine](https://user-images.githubusercontent.com/23633802/64129570-27b1fd80-cdbd-11e9-9028-c514eb51de71.png)

Le coordinate possono anche essere nulle

**Comment by corradinia91** [comment]
Ho capito cosa hai fatto. Tu hai fatto doppio click sulla mappa, e ti ha creato uno stabilimento nuovo. Poi hai tentato di salvarlo senza mettere l'indirizzo o il company name
![immagine](https://user-images.githubusercontent.com/23633802/64130107-7ca34300-cdc0-11e9-9367-4711935b054a.png)

L'errore è che doveva visualizzarti i campi errati in rosso come nello screen precedente. La mia ricostruzione è corretta?

**Comment by bacca87** [comment]
no, io ero presente, ha usato il mirino per prendere le coordinate lat/lng su uno stabilimento esistente, una volta presa la coordinata, ha fatto salva.

**Comment by corradinia91** [comment]
Quindi ha selezionato uno stabilimento e poi doppio click sulla mappa?
Anche se selezioni uno stabilimento e poi fai doppio click ti crea uno stabilimento nuovo. 
![immagine](https://user-images.githubusercontent.com/23633802/64130318-e5d78600-cdc1-11e9-8a9f-8fa67fffb272.png)

Da quello che vedo per modificare le coordinate di uno stab esistente devi usare il comando sul pannello edit

![immagine](https://user-images.githubusercontent.com/23633802/64130297-c2acd680-cdc1-11e9-83aa-6e27770f8072.png)

**Comment by bacca87** [comment]
nessun doppio click. selezioni uno stabilimento, poi nel pannello di modifica c'è un pulsantino con un + e poi devi cliccare un punto a caso sulla mappa e ti prende quella coordinata. poi fai salva

**Comment by corradinia91** [comment]
Ha l'ultima versione? perchè a me funziona. Da codice lo stabilimento è valido se il nome, l'indirizzo e la ragione sociale sono diversi da null

**Comment by BoniniJ** [comment]
Si ho l'ultima versione, praticamente non mi salvava perchè la colonna "Company Name" era vuota. Ho riprovato ora con quella colonna compilata e mi salva correttamente le coordinate prese manualmente.

**Comment by bacca87** [comment]
Ok, il campo company name non è obbligatorio in realtà, non serve a nulla. l'importante è che venga compilato il nome, l'indirizzo e il tipo di trasferta. 
Inoltre il messaggio di errore sarebbe meglio che fosse piu preciso per capire subito il problema.

**Comment by corradinia91** [comment]
Dietro al messaggio i campi errati devono essere visualizzati in rosso. Sto guardando il perchè non lo fa, ma direi che non serve scrivere cosa è sbagliato quando vengono evidenziati i campi. Tolgo il companyname dalla validazione
