### ISSUE TITLE
Titolo eventi

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#106]
Attualmente il titolo per gli eventi è obbligatorio, però su sharepoint non lo si puo settare perche viene creato in automatico.
A sto punto non so quanto serva far inserire il titolo all'utente visto che normalmente non può farlo.

Da valutare.

**Comment by masierim** [comment]
sempre visto ieri, cavalo!

**Comment by corradinia91** [comment]
L'utente può inserire il titolo anche da interfaccia sharepoint, poi è il server che lo sovrascrive. L'ho tenuto per compatibilità di interfaccia. Inoltre mettere un titolo sensato su great permette all'utente di dare un senso all'evento stesso. Io lo uso, e mi è comodo

**Comment by bacca87** [comment]
Secondo me messa cosi puo confondere.

Se io setto un titolo "pippo" e poi vado su sharepoint e non c'è scritto "pippo", mi disorienta o comunque mi fa incazzare perche io voglio che ci sia scritto pippo.
E poi teoricamente se tu aggiorni i valori da sharepoint, dovrebbe sovrascrivere il tuo titolo no?
Se non è cosi allora non siamo piu compatibili con l'interfaccia. Giusto?

Secondo me ci puo stare che uno metta delle note o commenti personali, ma in un campo aggiuntivo a parte, che sia chiaro che quella descrizione non va a finire su sharepoint.
Secondo me il titolo deve rimanere identico a quello di sharepoint poi, se vuoi commentare, aggiungiamo un campo note oppure si usa la descrizione dell'evento stesso.

**Comment by corradinia91** [comment]
Io aggiorno tutti i dati da sharepoint solo quando importo. Se l'evento è stato creato da great l'unica cosa che viene aggiornata è lo stato.

**Comment by bacca87** [comment]
quindi se io cambio dei dati dal sito web poi non vengono aggiornati su great?
Io posso collegarmi con il cellulare e modificare il periodo o aggiungere commenti che poi perderei su great.
Secondo me la situazione Great/Sharepoint deve sempre essere sincronizzata.

**Comment by corradinia91** [comment]
Si, hai ragione.
1) Per la questione del titolo potrà anche rimanere vuoto alla creazione dell'evento. Una volta inserito nel calendario sharepoint il titolo sarà aggiornato con quello su sharepoint. Eventuali note andranno messe in un nuovo campo note, che rimarrà a gestione interna di great
2) Per ogni evento su sharepoint  se viene modificato qualcosa 
(date, titolo, location, allday,description)
verrà modificato anche l'evento su great.
