### ISSUE TITLE
Validazione date eventi

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#107]
Quando si inserisce una data di partenza, subito viene invalidata perche superiore a quella di fine.
Se si corregge la data di fine, l'errore di validazione rimane sempre attivo anche se l'errore non è piu presente.

![immagine](https://user-images.githubusercontent.com/6023494/64151961-d4c35f00-ce2b-11e9-9711-3fcdf100640e.png)

**Comment by masierim** [comment]
vero, l'ho visto anch'io ieri.
in più aggiungo che , una volta inserita la data di partenza, all'apertura del calendario della data di fine, sarebbe comodo che partisse dalla data start e non da oggi.
