### ISSUE TITLE
Kilometraggio noleggi

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#112]
Quando inserisco i km iniziali mi segnala errore perche devono essere inferiori ai km finali che sono 0 perche debbo ancora inserirli.
Se poi inserisco i km finali corretti, la validazione rimane evidenziata nonostante sia tutto ok.

Un altra considerazione è che i km finali devono poter essere inseriti anche a posteriori, questo perche uno puo inserire il noleggio anche prima di averlo effettivamente terminato.
Questo si fa quando si fanno trasferte lunghe, e quindi bisogna compilare piu FDL associati a quel noleggio, e quindi, per avere la compilazione della targa automatica, va inserito il noleggio prima del termine.

Io farei che se i KM finali sono = 0, ingnora la validazione, altrimenti controlla.

**Comment by corradinia91** [comment]
Ok,Nella validazione non saranno cosiderati i km finali se questi sono =0
