### ISSUE TITLE
Assegnazione automatica dell'automobile al FDL

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#113]
se un FDL ricade all'interno del periodo di un noleggio, associare la targa per la compilazione.

**Comment by masierim** [comment]
sei sicuro?
se ho preso due macchine?

**Comment by bacca87** [comment]
ne aggiungo 2, fa cosi anche il vecchio great

**Comment by bacca87** [comment]
facciamo che per il momento non spreco tempo a fare questa modifica visto che aggiungere o non aggiungere le targhe non cambia un cazzo e nessuno si lamenta.
