### ISSUE TITLE
Ridimensionamento >= 125%

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#120]
1) I grafici della prima pagina delle statistiche non si ridimensionano in altezza 
2) l'header del dettaglio timesheets 
3) Inserimento dati noleggi

cercare in giro per il programma altri elementi mal ridimensionati

**Comment by corradinia91** [comment]
Ridimensionamento grafici ne PR #126

**Comment by corradinia91** [comment]
Bisogna ridimensionare anche la pagina eventi
