### ISSUE TITLE
Calcolo Hours of Leave

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#123]
ho lavorato 6 ore e 30 minuti e mi calcola 1.70 di ore di permesso
foto in allegato

![image](https://user-images.githubusercontent.com/54029318/65406441-da371800-dddf-11e9-98d8-356ef396fb71.png)

**Comment by bacca87** [comment]
puoi indicarmi che orari hai inserito nello specifico?

**Comment by masierim** [comment]
![image](https://user-images.githubusercontent.com/54029318/65413361-964d0e80-ddf1-11e9-8267-f58342a94de0.png)

**Comment by bacca87** [comment]
sistemato, nella prossima release vedrai i conteggi corretti.
