### ISSUE TITLE
Personalizzazione colori dei caratteri

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#136]
Inserire la possibilità di impostare il foreground color dei caratteri per gli stati dei giorni.
Se uno ha il tema chiaro e seleziona un colore scuro, il testo diventa illeggibile, stessa cosa se uno ha il tema scuro e sceglie un colore chiaro.

![2019-10-04 10_09_23-Window](https://user-images.githubusercontent.com/6023494/66192519-f153f080-e690-11e9-8d26-c22768442925.png)

**Comment by corradinia91** [comment]
Assegnamela

**Comment by corradinia91** [comment]
Invece di permettere all'utente di assegnare il colore implementiamo il calcolo del colore migliore tra quelli di default del tema (chiaro e scuro).
