### ISSUE TITLE
Riorganizzazione Menu

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#138]
Secondo me migliorerebbe sia l'aspetto che la superfice visualizzabile se venissero spostati i menu in basso, in "cavalieri" in alto (Modello Applicativi Office).
Idem per la barra di stato per la connessione ad Exchange.
Vedi immagine di seguito

![Suggestions](https://user-images.githubusercontent.com/44894734/66398279-c8f42b00-e9dd-11e9-8bac-adb007eee494.PNG)

**Comment by bacca87** [comment]
Non si puo fare, ti spiego il perche:
Il menu che vedi sopra, emula il famoso menu Ribbon di microsoft, quello di office per intenderci. Quei tab che vorresti usare tu sono in realtà i tab relativi al menu, e servono per organizzare meglio gli strumenti con cui modificare i dati sotto. quando modificherai un FDL o NS vedrai apparire ad esempio un tab nuovo per salvare. In pratica navighi solo all'interno del menu stesso, non hai una navigazione a pagine. Le pagine sotto invece sono contenute in un Tab Control, che serve a separare contenuti dentro appunto a delle tab per facilitare la navigazione. Le pagine possono essere cambiate solo cliccando sui tab item in basso. Questi tab item possono essere disposti, sotto, a destra, a sinistra e sopra. Ho provato gia a posizionarli nelle altre posizioni ma fanno ribrezzo. La posizione in basso la adotta anche la versione di outlook 2013 da cui ho preso spunto. 

![3378233488](https://user-images.githubusercontent.com/6023494/66434013-e3e88e80-ea21-11e9-9738-45a79abe3c50.png)

Un layout come dici tu implicherebbe il ridisegnamento di tutta la GUI, oltre che alla customizzazione abbastanza pesante della stessa per supportare la navigazione totale a tab.
L'obbiettivo adesso è dare ai trasfertisti uno strumento stabile che possa rimpiazzare definitivamente il vecchio great, quindi dobbiamo accontentarci delle librerie gia pronte adattandoci al loro standard.
In futuro, quando il programma sarà stabile, avevo una mezza idea di rimpiazzare il ribbon con l'hamburger menu, vedremo...

**Comment by OMAR610** [comment]
Niente menu Efukt insomma...

**Comment by bacca87** [comment]
per quello bisognerà fare alla vecchia maniera... :D
