### ISSUE TITLE
Migration Failed! Exception...

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#139]
Errore all'avvio con Data Directory all'interno della cartella OneDrive.
Cliccando su OK, il processo va avanti ed il software si avvia senza problemi.

Migration Failed!
Exception: The process cannot access the file 'C:\Users\izzo.o\OneDrive - Elettric 80\.849C9593-D756-4E56-8D6E-42412F2A707B' because it is being used by another process.

![1](https://user-images.githubusercontent.com/44894734/66414585-ffd83a00-e9f9-11e9-9db9-c241f1df7040.PNG)

**Comment by bacca87** [comment]
mmmh strano... pensavo di averlo risolto definitivamente qui #121
Per caso avevi aperto il db con tool esterni tipo sqlite expert?

Ad ogni modo non è grave, semplicemente fallisce nel cancellare il vecchio db nella vecchia cartella, volendo puoi cancellarla a mano dentro "documenti".

Penso di aver capito dov'è il problema, domani lo fixo.

**Comment by bacca87** [comment]
no ho visto meglio ora lo screenshot che hai inserito, in realtà non è il db il problema ma un file temporaneo di onedrive!
Per caso hai provato a migrare da una cartella a un altra dentro onedrive?
In tal caso è un errore esterno!

**Comment by OMAR610** [comment]
Cambiato directory, non è più in onedrive.
Stesso errore:

Migration Failed!
Exception: The process cannot access the file 'C:\Users\izzo.o\Desktop\TEMP\.849C9593-D756-4E56-8D6E-42412F2A707B' because it is being used by another process.

![Cattura](https://user-images.githubusercontent.com/44894734/66489435-e8f41f00-eaaf-11e9-82ea-8e4c3f8ab093.PNG)

**Comment by bacca87** [comment]
E' stranissimo, ma che file è .849C9593-D756-4E56-8D6E-42412F2A707B? 
Great non genera sta roba, tra l'altro è lo stesso nome file del primo screenshot!

Ho provato a googlare e sembra un problema di onedrive:

https://answers.microsoft.com/en-us/windows/forum/all/one-drive-file-849c9593-d756-4e56-8d6e/98f470db-5142-43c4-a30b-4d76176d561d

direi che sia da ritenersi un bug esterno al programma.

**Comment by OMAR610** [comment]
Ho migrato un paio di volte ancora il tutto, ed ora l'errore si è dissolto.
Concordo che l'origine del problema forse è il tentativo di aggiornamento nel cloud di Onedrive...
Ora tutto ok comunque.
