### ISSUE TITLE
statistiche 

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#143]
•	Bugs
- partire da zero con i grafici non da -20
- allineare nel centro del grafico il proprio titolo

•	Improvements

- nei grafici a torta . fare visualizzare, in lista, i giorni contati . per esempio : quando vado sopra con il mouse mi appare il tooltip con la lista dei giorni che fanno parte di quel gruppo.
- in hours by type mettere il totale come worktime overview
- aggiungere i giorni di trasferta per mese

**Comment by bacca87** [comment]
relativo a #19

**Comment by corradinia91** [comment]
1) Secondo me nel grafico "Hours By Type" non ha senso avere il totale in quanto verrebbero considerate nel calcolo anche le ore di ferie/permesso. Per ora non lo mettiamo
2) Anche il conteggio dei giorni per tipologia nel mese è una info ridondante, per ora non la mettiamo.
3) Dalla prossima release se clicchi sui grafici a torta ti si aprirà un popup con il dettaglio dei giorni della tipologia selezionata.
![immagine](https://user-images.githubusercontent.com/23633802/68118396-3a050080-ff00-11e9-85ea-eb639ad2da8c.png)

**Comment by masierim** [comment]
>2. Anche il conteggio dei giorni per tipologia nel mese è una info ridondante, per ora non la mettiamo.

perchè ? dovè adesso ?

**Comment by masierim** [comment]
è rimasto un "-20" in Statistics >Kilometers

**Comment by corradinia91** [comment]
Il popup si apre anche se clicchi sulla mappa del mondo e sui tiles.
Nel grafico km  il -20 lo vedi perchè necessario a fare la curva della linea. Se lo tolgo la linea risulta tagliata malamente, ed è esteticamente inguardabile

**Comment by bacca87** [comment]
Il vero problema è che un grafico lineare dovrebbe essere usato per le sequenze di dati.
I km dei noleggi non sono sequenze, ma segmenti con inizio e fine non collegati tra di loro.
Il grafico piu adeguato per rappresentare questi dati è quello a colonne.

**Comment by bacca87** [comment]
Sarebbe cosa buona e giusta aggiungere la finestra dei dettagli anche su questi riepiloghi:

![immagine](https://user-images.githubusercontent.com/6023494/69153808-2bf9d700-0adf-11ea-9326-157ee9420ac9.png)

Inoltre correggerei una cosa: a me indica che ho lavorato 7 domeniche, in realtà non è vero perche quelle domeniche ero si in trasferta, ma non ho lavorato. Secondo me bisognerebbe contare solo i giorni in cui sono state inserite delle ore.
