### ISSUE TITLE
Creazione Milestone

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#150]
Necessario scrivere a fuoco nel codice, applicando anche combustubile fossile per rendere più evidente, che dalle 17h30 di oggi sono un utilizzatore al 100% di Great2, abbandonando di fatto Great1.
![Great](https://user-images.githubusercontent.com/44894734/66766039-728b5e80-eead-11e9-88e1-d9c42ebd5b5c.PNG)

**Comment by bacca87** [comment]
TOP, benvenuto nel club!
