### ISSUE TITLE
Virtual FDL

### ISSUE THREAD

**Issue by LelloSnello** [bacca87/great2#151]
Fagiani, ma se aggiungeste l'add di un FDL in modo manuale che va a generare un FDL virtuale che abbia tutti i dati inseriti a mano? sarebbe tutto al solo scopo di fare statistica per chi usava/usa Great (quello che funziona) già da molto tempo, quando ancora gli FDL erano di tipo incompatibile.

**Comment by bacca87** [comment]
Implementazione base fatta, manca da scegliere un icona per il bottone e inserire un flag nella lista dei FDL e NS che identifichi che quello specifico elemento è virtuale o no.
Inoltre se dovessero essere importati un FDL o NS con lo stesso ID di uno virtuale, trasformare il virtuale in normale FDL o NS. Disabilitare inoltre le notifiche baloon di windows per i virtuali. 

Valutare la creazione automatica dei FDL virtuali con l'importazione da great per i vecchi tipi di FDL e NS.

**Comment by bacca87** [comment]
manca solo la parte di importazione da great

**Comment by bacca87** [comment]
troppa sbatta, per fare l'import automatico da great per i FDL non supportati richiede parecchio tempo, che preferisco spendere per altre funzionalità piu utili.
