### ISSUE TITLE
Expander TIMESHEET INFO

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#153]
L'expander nella sezione TIMESHEET INFO funziona al contrario..

![_Great2-1](https://user-images.githubusercontent.com/44894734/67187579-cab0ec00-f3ea-11e9-8364-dbbac8d065f5.PNG)
![_Great2-2](https://user-images.githubusercontent.com/44894734/67187580-cab0ec00-f3ea-11e9-896b-6a4b4f3643a0.PNG)

**Comment by bacca87** [comment]
fixato

**Comment by masierim** [comment]
non funziona più. la barra con il titolo rimane sotto anche da aperto... o è voluto?

**Comment by bacca87** [comment]
è voluto, l'expander ora si espande nella direzione corretta per come è concepito quel componente.

**Comment by masierim** [comment]
Ok. Subito sembrava un errore… 😊 
Poi ho capito!

Inviato da Posta per Windows 10

Da: Marco Baccarani
Inviato: martedì 22 ottobre 2019 15:20
A: bacca87/great2
Cc: masierim; Comment
Oggetto: Re: [bacca87/great2] Expander TIMESHEET INFO (#153)

è voluto, l'expander ora si espande nella direzione corretta per come è concepito quel componente.
