### ISSUE TITLE
Stabilimenti centralizzati

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#155]
Ci vorrebbe una sezione condivisa, che potesse uniformare per tutti i nominativi ed gli indirizzi, mentre invece ora mi sembra di capire che è totalmente locale...

**Comment by bacca87** [comment]
Si gli stabilimenti sono locali, il vero problema è che anche a livello SAP non sono uniformati...
Capita spesso di ricevere per la stessa commessa, FDL con ragioni sociali e indirizzi diversi per indicare lo stesso identico cliente. Questo rende un incubo l'associazione automatica del FDL con lo stabilimento, o anche solo l'aggiunta automatica, che ora è disabilitata di default, ma attivabile dalle impostazioni. Per semplicità la gestione è stata lasciata a carico dell'utente. 
Ben venga se hai qualche idea su come potebbe essere gestito questo problema che ne valutiamo la realizzazione.

**Comment by OMAR610** [comment]
Eh.. Si, mi ricordo che c'era lo stesso identico problema in passato.
Boh, si potrebbe fare una db con associazione, clienti, comesse, indirizzi, e manutenerlo a mano in modo comune.
So che non è il top, ma potrei anche buttare giù una bozza...

**Comment by bacca87** [comment]
Cosi però bisogna centralizzare con un servizio online, e sono tutti a pagamento...
E poi la cosa peggiore sarebbe la retrocompatibilità, come fai poi l'associazione con quelli gia esistenti nello storico?

**Comment by bacca87** [comment]
chiudo perche inapplicabile con i dati a disposizione.
