### ISSUE TITLE
Expense Account in excel

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#156]
Possibilità di implementare la gestione tramite file (magari xls?) delle note spese anche per chi non riceve il ***R.pdf.
Notamente, le filiali o gli esterni non lo ricevono.

**Comment by OMAR610** [comment]
In allegato un File XLS che è usato per le note spese, ma per essere standard, adrebbe almeno tradotto in Inglese..
[00XXX XXXXX XXXXX XX XX 20XX Note Spese.xlsx](https://github.com/bacca87/great2/files/3749910/00XXX.XXXXX.XXXXX.XX.XX.20XX.Note.Spese.xlsx)

**Comment by bacca87** [comment]
i polacchi hanno una NS totalmente diversa, e ha validità mensile.
[Expense report_xxxxxx_tydzien2-3-4_ver16.xlsx](https://github.com/bacca87/great2/files/4173161/Expense.report_xxxxxx_tydzien2-3-4_ver16.xlsx)
