### ISSUE TITLE
CAR RENTAL

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#157]
Sostituirei il nome CAR RENTAL con un CAR MANAGEMENT.
Non sempre le auto sono a noleggio..

**Comment by bacca87** [comment]
quali sarebbero i casi non a noleggio? anche le carserver sono da considerarsi a noleggio...

**Comment by OMAR610** [comment]
A me è capitato di usare la mia auto personale spostamenti brevi.
In ogni modo facevo riferimento alle auto aziendali assegnate, che non sono mai da restituire.
Non che cambi molto, comunque..
