### ISSUE TITLE
Lista Autonoleggi

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#158]
Possibilità di espandere la lista delle società di noleggio.
Ce ne sono di più di quelli indicate, e capita che in certi casi vengano scelte compagnie locali (Come ad esempio spesso succede in Germania, dove l'Area Manager ha fatto convenzioni dedicate.)

**Comment by bacca87** [comment]
Si potrebbe pensare di gestire la cosa come per i modelli auto, con un semplice campo di testo con autocompletamento. Cosi uno inserisce quello che gli pare.
Questo renderebbe inutile la tabella CarRentalCompany sul db, che si potrebbe rimuovere definitivamente.

@corradinia91 cosa ne pensi? credi ci voglia molto implementare una gestione cosi?

**Comment by corradinia91** [comment]
No, non ci vuole molto. Lo facciamo... assegnamela
