### ISSUE TITLE
modifica tipo giorni

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#159]
se cambio un tipo giorno da vacation a special leave, al riavvio non tiene le modifiche tornando così vacation.

**Comment by corradinia91** [comment]
Il giorno che stai modificando è incluso in una richiesta ferie di sharepoint?

**Comment by masierim** [comment]
Sicuramente, essendo assente ho dovuto per forza fare una richiesta di ferie. Ma non sono ferie!
Inviato da Posta per Windows 10

Da: Andrea Corradini
Inviato: martedì 22 ottobre 2019 14:27
A: bacca87/great2
Cc: masierim; Author
Oggetto: Re: [bacca87/great2] modifica tipo giorni (#159)

Il giorno che stai modificando è incluso in una richeista ferie di sharepoint?

**Comment by corradinia91** [comment]
Bacca assegnamela. Il problema è la sincronizzazione di sharepoint. Possiamo fare in modo che la sincronizzazione non modifichi il tipo giorno qualora l’utente lo abbia impostato manualmente

**Comment by bacca87** [comment]
Ma ha senso mettere uno special leave in un giorno di ferie?? sono 2 cose totalmente diverse, significa che la richiesta ferie è sbagliata e andrebbe annullata.
Io proprio bloccherei la possibilità di cambiare stato ai giorni segnati di ferie. se uno li vuole modificare e trasformarli in altro tipo, annulla e poi modifica.

**Comment by corradinia91** [comment]
Adesso se il tipo giorno viene modificato dopo l'approvazione, non viene più sovrascritto
