### ISSUE TITLE
Check aggiornamenti automatici e import

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#161]
Disabilitare momentaneamente il check degli aggiornamenti automatici mentre ci sono degli import in corso tipo Great o fdl da file.

**Comment by corradinia91** [comment]
Mettere anche un pulsante di check aggiornamenti manuale. Capita che a volte l'aggiornamento automatico arrivi in ritardo

**Comment by bacca87** [comment]
gli aggiornamenti li controlla ogni 2 minuti, nel caso peggore si aggiorna dopo 4 min.... direi che è accettabile. Il check forzato non è cosi banale da implementare.
Potremmo valutare di fare un check ogni minuto.
