### ISSUE TITLE
riquadro Edit

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#163]
mettete a posto quello schifo di riquadro Edit, quando selezioni un giorno di una tipologia non Work?
fa veramente pena, ma chi ha deciso di fare un lavoro del genere? Bacca sei stato te? solo te potresti fare una cosa del genere. sei proprio un Pezzaro....

**Comment by bacca87** [comment]
Quando si seleziona un giorno di ferie succede questo brutto effetto grigio nel form di compilazione ore:

![immagine](https://user-images.githubusercontent.com/6023494/67299808-67f44900-f4ed-11e9-8153-c34afe1edca9.png)
