### ISSUE TITLE
Timesheet info e Edit

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#164]
Timesheet info : si può nascondere in automatico quando, per esempio, scorro i giorni?
Edit:  si può aprire quando fai doppio click sul'inserimento? o sempre quando apri il Timesheet info ?

**Comment by bacca87** [comment]
per chiarezza: Il pannello di inserimento ore, se chiuso, non si apre facendo doppio click sul record del timesheet. Quello che chiede michele è di aprirlo con il doppio click.

Per la chiusura automatica del pannello dei Timesheet bisogna valutare come fare, basarsi semplicemente sullo scorrimento non è una soluzione solida, ma si puo fare in altri modi, magari gestendo anche un flag per tenerlo sempre aperto se uno ne ha l'esigenza (es. copiare e incollare diversi giorni)

**Comment by bacca87** [comment]
la parte del pannello edit è stata fatta, manca da ragionare sull hide automagico.

**Comment by bacca87** [comment]
la chiusura del pannello dei timesheets puo essere comandata premento il tasto esc, è il compromesso migliore.
