### ISSUE TITLE
Anomalia dopo importazione manuale FDL

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#166]
Dopo aver importato un FDL manualmente: 

Salvato in una directory sul desktop e poi indicata come directory di importazione attraverso il menu Import/Export.

Il suddetto FDL viene marcato come "Accepted" anche se non è stato compilato, ed non è stato forzato "Accepted" manualmente.

![Cattura](https://user-images.githubusercontent.com/44894734/67318499-dba54e80-f50b-11e9-83e1-b8f01c1e21a0.PNG)

**Comment by bacca87** [comment]
Si, marca come accepted perchè quella funzionalità era stata concepita per importare FDL già compilati con lo scopo di aggiungerli allo storico, però effettivamente non avevo considerato il fatto che qualcuno potrebbe importare un FDL nuovo mai inviato.
Il vero problema è che io di quei FDL non ne conosco il reale stato, e per comodità metto tutto come "Accepted" cosi chi importa non ci mette 2 anni a marcare manualmente centinaia di FDL con il loro stato corretto. Anche se un FDL viene marcato come accepted, comunque nessuno ti vieta di compilarlo e reinviarlo con i dati corretti.
Quindi o si trova un modo per distinguere un FDL "nuovo" da uno "vecchio" oppure il male minore rimane mantenere tutto come ora.

**Comment by OMAR610** [comment]
Beh, un FDL nuovo è un FDL con anno corrente e numero settimana uguale o superiore alla attuale.
Un FDL vecchio è un FDL con settimana inferiore a quella attuale se anno corrente, oppure qualsiasi numero settimana se anno inferiore a quello attuale..

**Comment by bacca87** [comment]
Si, potrebbe andare... 
Rimarrebbe comunque il problema che se uno arriva lungo e lo importa la settimana dopo, verrebbe marcato come "Accepted". 
Oppure se uno importa un FDL che ha gia inviato a sistema la settimana corrente, verrebbe marcato come "New".

**Comment by OMAR610** [comment]
Beh, mi sembra comunque accettabile.
Inoltre a breve nessuno più importerà FDL che ha già inviato, poichè tutti useranno Great.
