### ISSUE TITLE
conteggio ore errato

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#168]
viene data la possibilità di mettere lo stesso orario sia in work start time che in work end Time e l'effetto è questo
![image](https://user-images.githubusercontent.com/54029318/67391086-2e2f4b00-f59e-11e9-98ec-cfdcfef176f5.png)

**Comment by bacca87** [comment]
non si capisce un cazzo ne dallo screen, che è segato, ne dal testo che non ha nessun esempio numerico.

**Comment by masierim** [comment]
cosa dici? si capisce benissimo invece ...
se guardi bene puoi notare che ho potuto mettere 8:00 sia in work start time che in  work end Time e lui mi ha contato 24:00
