### ISSUE TITLE
Importazione FDL da mail non funzionante

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#169]
L'importazione del FDL non funziona, anche se viene riconosciuto lo stato di Syncronized:

![1](https://user-images.githubusercontent.com/44894734/67588906-89586d80-f757-11e9-9938-5e01b5450112.PNG)

![2](https://user-images.githubusercontent.com/44894734/67588910-8cebf480-f757-11e9-8179-a72bd3061085.PNG)

Di seguito info utili:

Received: from srv-e80exc01.elettric80.lan (172.25.2.77) by
 srv-e80exc02.elettric80.lan (172.25.2.78) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) id 15.1.1531.3
 via Mailbox Transport; Fri, 25 Oct 2019 17:00:07 +0200
Received: from srv-e80exc01.elettric80.lan (172.25.2.77) by
 srv-e80exc01.elettric80.lan (172.25.2.77) with Microsoft SMTP Server
 (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256) id
 15.1.1531.3; Fri, 25 Oct 2019 17:00:07 +0200
Received: from sap.elettric80.it (172.24.0.119) by srv-e80exc01.elettric80.lan
 (172.25.2.77) with Microsoft SMTP Server id 15.1.1531.3 via Frontend
 Transport; Fri, 25 Oct 2019 17:00:07 +0200
Date: Fri, 25 Oct 2019 16:53:49 +0200
From: SAP MAIL <fdl@elettric80.it>
Subject: 10270  IZZO OMAR 90000772 44 10 2019
To: <IZZO.O@ELETTRIC80.IT>, <FDL_CHK@ELETTRIC80.IT>
Message-ID: <ADR440000000564311000050568674001ED9BDE704427EF2C316@sap.elettric80.it>
MIME-Version: 1.0
Importance: Normal
X-Priority: 1 (Highest)
X-Mailer: SAP NetWeaver 740
Content-Type: multipart/mixed; boundary="=_0050568674001ED9BDE704427EF2E316"
Return-Path: fdl@elettric80.it
X-MS-Exchange-Organization-Network-Message-Id: 7cf5516a-6c1a-4044-fcb9-08d7595c066a
X-MS-Exchange-Organization-AuthSource: srv-e80exc01.elettric80.lan
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-Exchange-Transport-EndToEndLatency: 00:00:00.2207972
X-MS-Exchange-Processed-By-BccFoldering: 15.01.1531.003

**Comment by OMAR610** [comment]
Senza un reale motivo che giustifichi, oggi ha importato tutto senza problemi...

**Comment by bacca87** [comment]
sei sicuro che il FDL non fosse mischiato insieme agli altri? forse c'è un bug di questo tipo...

**Comment by OMAR610** [comment]
In che senso mischiati?

**Comment by bacca87** [comment]
stesso problema del #154

**Comment by bacca87** [comment]
mischiato nel senso in mezzo ai FDL gia accettati, oppure semplicemente in fondo alla lista invece che sopra

**Comment by OMAR610** [comment]
Non mi pare.
Era semplicemente non importato.
