### ISSUE TITLE
Pulsante selezione giorno attuale

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#171]
Il pulsante di selezione del giorno attuale, sarebbe più "simpatico" se indicasse al suo interno il numero del giorno in questione ed anche il nome del giorno...
Una cosa simile:

![photo_2019-10-28_12-39-18](https://user-images.githubusercontent.com/44894734/67675658-fcdcc380-f97f-11e9-9745-404cc0e6b64b.jpg)

**Comment by bacca87** [comment]
Ho  provato a vedere se era possibile customizzare a questo livello il componente che usiamo per il menu, però putrroppo i template dei bottoni non sono modificabili.
