### ISSUE TITLE
Copia e Incolla Timesheets

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#18]
controllare che se si copia un giorno con fdl associato, questo FDL non venga ricopiato in un giorno di una settimana a cui non puo essere utilizzato.

**Comment by corradinia91** [comment]
Se copi un timesheet in un nuovo giorno e poi modifichi quest'ultimo ti cambia entrambi i timesheet

**Comment by corradinia91** [comment]
Da chiudere
