### ISSUE TITLE
Fatal Error dopo Update Great2 Beta >= 1.1.524

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#182]
Impossibile avviare Great dopo ultimo update del 04.11.2019.

:(

![1](https://user-images.githubusercontent.com/44894734/68138519-038fab80-ff29-11e9-8d64-b1c5f7e3f10e.PNG)

**Comment by masierim** [comment]
allora non aggiorno..... =)

**Comment by bacca87** [comment]
Se hai giá aggiornato a mano il cfg dentro appdata/local/great2 e ti da questo errore, devi disinstallare e reinstallare great. Una volta reinstallato risistema il cfg e dovresti essere in bolla.
 
@masierim è inevitabile, devi aggiornare e sistemare a mano il problema. è una cosa inevitabile, non succederá piu in futuro.

**Comment by OMAR610** [comment]
Installato ex novo, e l'errore me lo da senza che io abbia aggiornato "a mano" il cfg.
Inoltre non capisco cosa intendi per aggiornare il cfg a mano...
Potresti spiegare meglio?
I 2 CFG sembrano totalmente incompatibili (vedi screenshot qui sotto)..

![1](https://user-images.githubusercontent.com/44894734/68155474-1070c700-ff4a-11e9-988b-968467cea41b.PNG)

![2](https://user-images.githubusercontent.com/44894734/68155479-149ce480-ff4a-11e9-8a03-209eb319fe88.PNG)

**Comment by OMAR610** [comment]
Ok, ho mergiato i 2 XML nelle parti compatibili, poi ho spostato la directory di Great2 nel percorso standard, e tutto è ripartito.

Però gli utenti a cui ho fatto installare great nelle scrose settimane, non ci salteranno fuori a fare una cosa così...


- [POSTIVO] Finalmente FDL importati istant
- [POSITIVO] Notifiche Toast
- [NEGATIVO] Serve spiegare come ripristinare, e la maggior parte degli utenti (non dev), rinunceranno e disinstalleranno ancora prima di capire come fare a far funzionare di nuovo Great2.

**Comment by bacca87** [comment]
Il parametro da modificare è "DataDirectoryPath" con l'indirizzo completo della cartella con i dati, il resto lo reimpostate dalla finestra dei settings.

Questo lo devono fare solo coloro che hanno spostato la cartella dei dati dalla posizione default. Gli altri dovranno solo reimpostare gli stili.

**Comment by OMAR610** [comment]
Io ho copiato tutta l'intera parte user settings dal config che era nella cartella di great2.

**Comment by bacca87** [comment]
va bene lo stesso, hai solo scelto la "hard way"

**Comment by OMAR610** [comment]
In assenza di istruzioni...

**Comment by OMAR610** [comment]
Risolto comunque, chiudo.

**Comment by masierim** [comment]
giusto per la cronaca, a me ha aggiornato senza problemi

**Comment by OMAR610** [comment]
Perché probabilmente non avevi custimizzato la directory di lavoro.
Io ho tutto dentro onedrive.

**Comment by bacca87** [comment]
lasciamo aperto cosi se altri hanno questo problema possono scrivere qui

**Comment by bacca87** [comment]
# GUIDA RISOLUTIVA 

1. Entrare nella cartella: C:\Users\{TUO_UTENTE}\AppData\Local\Great2\Great2.exe_Url_{hash alfanumerico}
2. All'interno della cartella individuare quella della versione appena installata (es. 1.1.529.0)
3. Aprire con il notepad il file user.cfg e modificare o aggiungereil seguente tag con il percorso assoluto della cartella in cui avete i files di great:
(es. _C:\Users\baccarani.m\OneDrive - Elettric 80\Great2_)

```
<setting name="DataDirectoryPath" serializeAs="String">
	<value>C:\Users\baccarani.m\OneDrive - Elettric 80\Great2</value>
</setting>
```

Una volta eseguiti questi passi dovrebbe ripartire tutto normalmente. 

**N.B** _Questa guida ripristina il funzionamento, purtroppo però le impostazioni della versione precedente verranno perse e le dovrete reinserire dalla pagina "Settings"._
