### ISSUE TITLE
finestre popup

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#183]
è possibile con [ESC] far chiudere le finestre?

**Comment by bacca87** [comment]
cosa intendi con finestre popup?

**Comment by masierim** [comment]
quello che intende anche Corra in :

>statistiche
#143
Dalla prossima release se clicchi sui grafici a torta ti si aprirà un popup con il dettaglio dei giorni della tipologia selezionata

in sostanza le finestre che apro dal programma, tipo la nuova details view .

**Comment by bacca87** [comment]
si è possibile

**Comment by corradinia91** [comment]
Assegnamela
