### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#184]
dopo aver importato i dati da i vecchi FDL non è possibile navigare negli anni  passati in Statistiche . mi crasha senza motivo

**Comment by bacca87** [comment]
io sto ancora aspettando la tua cartella di great

**Comment by bacca87** [comment]
Il problema è stato risolto, in pratica scoppiava perche ci sono degli stabilimenti con nome duplicato.
In attesa della prossima pubblicazione, se vuoi vedere i dati del 2018, ti consiglio di togliere tutti i nomi duplicati dagli stabilimenti. Dalla prossima versione, anche se ci saranno nomi duplicati, le statistiche verranno visualizzate comunque correttamente.
