### ISSUE TITLE
miglioramento Details View

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#185]
se possibile ,mettere numero settimana anche ai gruppi di giorni che non iniziano con lunedì 
raggruppando per giorni contigui
![image](https://user-images.githubusercontent.com/54029318/68186721-19db4d00-ffa5-11e9-96d5-b2cc9293d8f5.png)

**Comment by bacca87** [comment]
i giorni sono gia contigui, manca solo il numero settimana

**Comment by corradinia91** [comment]
Assegnamela

**Comment by corradinia91** [comment]
Lo facciamo per tutti i giorni però, non solo al primo del gruppo

**Comment by masierim** [comment]
Il top sarebbe al primo del gruppo, poi vedi te…..

Inviato da Posta per Windows 10

Da: Andrea Corradini
Inviato: martedì 5 novembre 2019 17:31
A: bacca87/great2
Cc: masierim; Author
Oggetto: Re: [bacca87/great2] miglioramento Details View (#185)

Lo facciamo per tutti i giorni però, non solo al primo del gruppo

**Comment by masierim** [comment]
Riesci a mettere anche il “vai a…” quando clicchi sul giorno ?


Inviato da Posta per Windows 10

Da: Andrea Corradini
Inviato: martedì 5 novembre 2019 17:31
A: bacca87/great2
Cc: masierim; Author
Oggetto: Re: [bacca87/great2] miglioramento Details View (#185)

Lo facciamo per tutti i giorni però, non solo al primo del gruppo

**Comment by masierim** [comment]
@corradinia91 ti sei impegnato molto. bravo... ma il numero settimana su tutti i giorni è incomprensibile . dovresti farlo così ( anche non subito .priorità bassa). grazie

![image](https://user-images.githubusercontent.com/54029318/68480275-b36c5e00-0234-11ea-8875-00da6d55ac9e.png)
