### ISSUE TITLE
Statistiche

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#19]
Completare la pagina delle statistiche

**Comment by corradinia91** [comment]
Vedi #54

**Comment by corradinia91** [comment]
Sul grafico most visited countries mettere la selezione europa/mondo e mettere i pulsanti di selezione grafico sul ribbon

**Comment by bacca87** [comment]
siam sicuri che serva? non basta lasciare mondo e bona le?

**Comment by corradinia91** [comment]
Problema risolto: Ci sono solo quelle dei singoli stati
