### ISSUE TITLE
FDL problema con piu fdl per lo stesso cantiere

### ISSUE THREAD

**Issue by flyfree861** [bacca87/great2#190]
Great2 ha scaricato tre fogli di lavoro 10677-10676 e 10675 tutti per il medesimo cantiere.
io prima avevo già scritto gli orari nella sezione timesheets ed erano cosi inseriti:
-Viaggio domenica 3 Novembre FDL 10675 settimana 44
-Settimana di lavoro e viaggio di ritorno FDL 10676 settimana 45 da lunedì a giovedi.

ora quando vado ad inserire gli orari della domenica 3 novembre nella sezione "timesheets" nel riquadro "EDIT", nella combobox "FDL" mi compare solo il FDL  10676 quando dovrebbe invece darmi il FDL 10675 che è quello relativo alla domenica.
nel momento in cui clicco compila tale domenica viene inserita nella domenica del FDL 10676
Mentre invece per le note spese tutto funziona correttamente.

![Per Github](https://user-images.githubusercontent.com/27213699/68456322-c31c8000-01fd-11ea-9eac-85b954fa792f.PNG)

**Comment by bacca87** [comment]
mi riesci a dare i nomi completi dei 3 files dei FDL?

**Comment by flyfree861** [comment]
ok ti allego screenshot
![per bacca](https://user-images.githubusercontent.com/27213699/68463695-80fc3a00-020f-11ea-838e-3b9ab2fac52e.PNG)

**Comment by bacca87** [comment]
Questo problema è stato causato da questa modifica #177, adesso vedo di sistemare.
