### ISSUE TITLE
Edit timesheet

### ISSUE THREAD

**Issue by corradinia91** [bacca87/great2#195]
Non è possibile modificare un ts senza eliminarlo. Si è rotto qualcosa

**Comment by bacca87** [comment]
io riesco a modificarli, spiegati meglio.

**Comment by corradinia91** [comment]
Quando tento di modificare un ts con fdl associato mi dice che si
sovrappone con un altro ts

Il giorno mer 20 nov 2019 alle ore 09:54 Marco Baccarani <
notifications@github.com> ha scritto:

**Comment by bacca87** [comment]
vero, il bug è stato introdotto con la modifica per questo ticket #148

**Comment by bacca87** [comment]
ho sistemato, valutiamo un rilascio.
