### ISSUE TITLE
Richiesta nuova funzionalità [Autoavvio con SO]

### ISSUE THREAD

**Issue by OMAR610** [bacca87/great2#211]
Ma se Great2 avesse tra le opzioni, "un lancia automaticamente all'avvio dell sistema operativo"?
HKCU:Run et cetera et cetera?

**Comment by bacca87** [comment]
per rendere la cosa meno fastidiosa, direi che bisogna aggiungere anche la possibilità di avviare iconizzato e senza splashscreen.
