### ISSUE TITLE
Salvataggio dati

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#39]
Quando qualcuno modifica un FDL o un EA o qualsiasi cosa in generale senza poi salvare, valutare il da farsi. Capire se mantenere le modifiche fatte senza salvarle sul db, oppure se far uscire un warning che abbandonando la pagina si perderanno le modifiche.

**Comment by bacca87** [comment]
se uno modifica una EA senza salvare, quando ritorna sulla EA si ritrova la modifica nella tabella senza possibilità di salvarla se non modificando qualcosa.

**Comment by corradinia91** [comment]
L'ultimo punto è stato risolto. Quando torni sulla ea e clicchi su uno dei campi da modificare torna fuori subito il menu contestuale con il comando save. Dobbiamo decidere solo come comportarci nel caso di modifiche incomplete. Io metterei un pulsante di discard changes nel menu contestuale, a fianco del pulsante salva

**Comment by bacca87** [comment]
Secondo me la soluzione migliore sarebbe quella che, se cambi selezione o pagina, ti esce un warning che ti avvisa dicendoti: "Ci sono modifiche non salvate, le modifiche non salvate verranno perse. Vuoi salvare?" e li l'utente sceglie cosa fare.

**Comment by corradinia91** [comment]
Si, però devi considerare che l'utente può modificare più di un'entità, pertanto tutte le modifiche devono essere scartate, non solo quelle dell'ultima selezionata

**Comment by bacca87** [comment]
cosa vuol dire piu di un entita? uno puo modificare un fdl alla volta o una nota spese alla volta.

**Comment by corradinia91** [comment]
Intendo che l’utente modifica il fdl A, non salva e poi seleziona B. Quando cambia pagina devi scartare le modifiche di entrambi i fogli

Ottieni Outlook per iOS<https://aka.ms/o0ukef>

________________________________
Da: Marco Baccarani <notifications@github.com>
Inviato: mercoledì, agosto 28, 2019 2:59 PM
A: bacca87/great2
Cc: Andrea Corradini; Comment
Oggetto: Re: [bacca87/great2] Salvataggio dati (#39)


cosa vuol dire piu di un entita? uno puo modificare un fdl alla volta o una nota spese alla volta.

**Comment by bacca87** [comment]
I FDL vanno inviati a sistema entro il lunedi successivo, uno solitamente modifica un FDL alla volta. Per le NS, anche se ne compili 6 assieme, comunque ne fai una alla volta.
Se invece hai esigenze particolari e devi modificare 2 FDL assieme, apri il primo, lo modifichi, premi salva, apri il secondo, lo modifichi, premi salva. Cosi facendo non appare nessun popup.
