### ISSUE TITLE
Statistiche

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#54]
nella grafica "year Statistic" inserire le ore di Vacations

**Comment by corradinia91** [comment]
Stiamo valutando come farlo. Nel grafico year statistic risulterebbe poco leggibile: la bar delle ferie sarebbe di qualche mm in confronto a quella delle ore.

**Comment by masierim** [comment]
ok, ma anche se non è propriamente in scala non penso che sia un problema....
si può mettere una dimensione minima? 
d'altronde anche le ore di straordinario, se fatte poche, è minima.
 però, almeno,  così me lo ritrovo sulle statiche nel popup che viene fuori quando ci vado sopra con il mouse....

**Comment by bacca87** [comment]
Il grafico a barre "year statistics" (che cambierà nome perche non vuol dire niente) serve ad avere un idea delle ore **lavorate** suddivise per tipologia. Le ore di ferie o di permesso non possono essere inserite in quel grafico perche ne sballerebbe i valori. Le ore di ferie non possono essere sommate a quelle di lavoro.

Per avere un resoconto delle ore per tipologia, bisogna creare un grafico a parte, oppure un semplice totale sotto forma di testo. Ad ogni modo come ha gia risposto corra, stiamo re-impaginando ed ampliando le statistiche, e nelle prossime versioni saranno piu complete.

**Comment by corradinia91** [comment]
Nuova pagina statistiche:

Tab Hours:
![immagine](https://user-images.githubusercontent.com/23633802/65389772-bdf09800-dd59-11e9-9d38-c6001430b252.png)

Cambiati i nomi dei grafici e aggiunto il grafico per tipologia ore

Tab Factories:

![immagine](https://user-images.githubusercontent.com/23633802/65389797-e6789200-dd59-11e9-834a-c6eea22c3d9e.png)

Devo finire di impaginarlo bene. Ho aggiunto la mappa con i paesi più frequentati. Per quel tipo di grafico ancora non esiste una legenda. Il paese più scuro è il più visitato.

Ho anche aggiunto un indicatore del numero di giorni in trasferta

Che ne dite, può andare? è  già nel PR

**Comment by bacca87** [comment]
ma che monitor hai? un ultra wide screen?

![samsung-chg90-ultrawide-monitor-review-5488-1920x1080](https://user-images.githubusercontent.com/6023494/65406177-02724700-dddf-11e9-8bec-13b487773b17.jpg)

comunque le tab "hours", "factories", "Kilometers" etc vanno nascosti e messi i bottoni nel menu sopra.

**Comment by bacca87** [comment]
cmq il thread ufficiale per le statistiche è il #19, questo ticket deve essere chiuso perchè è gia stata data una risposta al problema.
