### ISSUE TITLE
inserimento ore in timesheets

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#55]
potrei consigliare di eliminare la tavolozza in basso a dx dove inserire le ore e sostituirlo con un più comodo inserimento direttamente nel riquadro in basso (quello a fianco per intenderci, dove si vede il dettaglio delle ore inserite) .
un po' come si inserisce un nuovo record su SQL...
così che anche la modifica del record sia più comodo ed immediato
magari ci metti un bel + di fianco sulla riga vuota sotto ... tutto molto figo! =)
tasto destro per eliminare.

**Comment by bacca87** [comment]
Da valutare.
In realtà, quando ancora great era in fase embrionale, l'inserimento delle ore era come hai detto tu, però ho scelto di fare un cambio di rotta per una questione di chiarezza ed usabilità.
L'inserimento a tabella dei dati ha pro e contro: è sicuramente piu immediato, però è anche piu facile sbagliarsi cliccando sulle caselle sbagliate o inserendo le ore nella tipologia sbagliata. 
La form in stile Great di cina è piu familiare agli utilizzatori, che non devono cambiare le loro abitudini di inserimento e permettono una transizione al nuovo great piu veloce ed immediata.

**Comment by corradinia91** [comment]
Dal punto di vista dell'usabilità io preferisco la soluzione in stile vecchio great. Nulla vieta però di adottare entrambe le soluzioni.
Per ottimizzare lo spazio disponibile ho fatto una prova usando dei tab espandibili. Di default è tutto espanso. L'utente può scegliere di comprimere i pannelli se vuole una consultazione a schermo intero della griglia timesheet o timesheet info.
Cosa ne pensate?

![Espanso](https://user-images.githubusercontent.com/23633802/63041826-01d5bf00-bec9-11e9-9569-ee8a367d07c9.PNG)


![Edit compresso](https://user-images.githubusercontent.com/23633802/63041828-01d5bf00-bec9-11e9-82dd-1149e638fd04.PNG)

![Compresso](https://user-images.githubusercontent.com/23633802/63041824-01d5bf00-bec9-11e9-9454-9961763f0fa0.PNG)

**Comment by masierim** [comment]
"a me me piace..." 
possiamo fare che con un doppio click sulla riga, di un qualsiasi giorno, si espanda tutto automaticamente per agevolare l'inserimento?

per quanto riguarda il metodo di inserimento se li metti tutti e due sei a posto.però vedete voi...
puoi , eventualmente, colorare i campi di "timesheets info" come fatto in "timesheets edit"...

**Comment by bacca87** [comment]
#60

**Comment by corradinia91** [comment]
Farle entrambe è uno spreco di spazio.. me ne sono reso conto nel farlo. Se si opta per la soluzione a riga tanto vale riciclare lo spazio attualmente usato per la form di inserimento ore per mostrare altre informazioni.  Visto l'abitudine degli utenti al vecchio great propongo di mantenere il sistema di inserimento attuale

**Comment by bacca87** [comment]
chiudo perche è stato fatto
