### ISSUE TITLE
timesheets - riga mese

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#56]
nella pagina timesheets , nella riga del mese si potrebbe inserire la somma delle ore per colonna

sarebbe molto comodo avere anche una indicazione dei giorni di trasferta fatti nel mese. non so se si riesce ad  inserire li anche quello. 

oppure un popup che viene fuori quando ci vai su con il mouse....

**Comment by bacca87** [comment]
I totali delle ore lavorate per mese si trovano già nella pagina delle statistiche sotto forma di grafico a barre. 

I giorni di trasferta per mese verranno inseriti nell'ampliamento delle statistiche.

Le informazioni statistiche sono tutte raggruppate in una sezione apposita perchè non utili per l'inserimento delle ore. Per avere tutti i resoconti del genere, si va nella sezione apposita a distanza di 1 click.
