### ISSUE TITLE
giorno giuliano 

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#63]
c'hai pensato?

**Comment by bacca87** [comment]
per cosa verrebbe usato?

**Comment by masierim** [comment]
la ricevuta dell'autostrada a volte è espressa in G.G. se guardi il vecchio great, andando sopra con il mouse al giorno, in alto a dx in "info box", viene fuori il giorno giuliano

**Comment by bacca87** [comment]
ok si puo fare, lo metto in lista
