### ISSUE TITLE
events list

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#65]
immagino che prima o poi implementerai la possibilità di ordinare la lista per colonna selezionata...
prima di questo, puoi invertire l'ordine ?
in modo da avere le più recenti in alto

**Comment by corradinia91** [comment]
Si, daremo la possibilità di ordinare per colonna. Nelle prossime release. Per ora l'ho fatto nella paina events e car rental

**Comment by masierim** [comment]
si può avere l'ordine decrescente della colonna start date all'apertura della finestra?
