### ISSUE TITLE
modifica indirizzo FDL ed EA

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#68]
in caso di collaudi in sedi diverse da elettric80, verrà inviato al tecnico un FDL ed EA con riferimento allo stabilimento di destinazione ma dovrà essere compilato con l'indirizzo della sede del collaudo(es. union14 via del lavoro Bosco di scandiano).

**Comment by corradinia91** [comment]
Stavo pensando ad una possibile soluzione. Per non rompere la relazione tra factory e fdl, la cosa più pulita è che l'utente crei a manina un nuovo factory e che lo associ al foglio. Great sovrascriverà l'indirizzo al foglio in oggetto. Può andare bene come soluzione?

Bacca, se non ci stai guardando tu assegnami l'issue

**Comment by bacca87** [comment]
Non so se è corretto sovrascrivere l'indirizzo a prescindere... 

Io potrei modificare l'indirizzo dello stabilimento perche voglio farlo visualizzare sulla mappa correttamente, però cosi facendo restituiamo al sistema fdl un fdl con un indirizzo diverso da quello inviato. Dite che fanno storie a riguardo?
Sicuramente per il caso a cui fa riferimento Michele è accettato, ma è lo stesso per tutti gli altri clienti?
Io valuterei piu approfonditamente la cosa.

**Comment by corradinia91** [comment]
La modifica l'ho fatta.Aspetto di inviare qualche fdl a sistema per vedere che funzioni prima di committarla

**Comment by bacca87** [comment]
ho un idea:
potremmo mettere un flag "Override Address" negli stabilimenti che, se selezionato, per quello specifico stabilimento all'invio del FDL o EA sovrascrive l'indirizzo altrimenti no.
A mio parere cosi sarebbe molto meno invasivo. Cosa ne pensate?

**Comment by masierim** [comment]
si ma solo per quel FDL non per tutti gli FDL di quello stabilimento....

**Comment by bacca87** [comment]
No invece per tutti quelli associati allo stabilimento con il flag selezionato. 
Se tu associ "bosco di scandiano" a un FDL o a 100 FDL, per tutti quelli verrà sostituito l'indirizzo.
Se invece associ al FDL lo stabilimento in cui verranno installate quelle macchine (cliente), allora l'indirizzo rimarrà invariato perche per quello stabilimento il flag non è stato settato.

**Comment by masierim** [comment]
ah, ok, ma quindi  io avrò nella pagina timesheets "bosco di scandiano" o "celtex" ?,

**Comment by bacca87** [comment]
nella timesheets avrai bosco di scandiano

**Comment by corradinia91** [comment]
Si può fare, ma che svantaggio ti da sovrascrivere l'indirizzo con una stringa uguale?

**Comment by bacca87** [comment]
la stringa non è per forza uguale, io la posso modificare a piacimento negli stabilimenti per far apparire i marker sulla mappa. di solito gli indirizzi dei FDL sono scazzati o scritti da merda e nessun programma di mappe riesce a geolocalizzarli. il flag è la soluzione piu pulita.

**Comment by corradinia91** [comment]
Lavoro sul flag, assegnami l'issue plz
