### ISSUE TITLE
popup di aggiornamento

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#69]
sistemare il pulsante "ricordamelo in seguito"

PS non sarebbe meglio mettere un inglese?

![image](https://user-images.githubusercontent.com/54029318/63025868-633a6580-beaa-11e9-8dfb-a01fedcc3b11.png)

**Comment by corradinia91** [comment]
Questa è un pacchetto nuget non nostro, quindi non possiamo modificarlo. Vediamo se è possibile cambiare la culture della lingua

**Comment by bacca87** [comment]
si l'avevo già notato, devo sentirmi con l'autore di quel componente per fare queste modifiche.

**Comment by bacca87** [comment]
Risolto, dalla prossima release la form sarà in inglese.

**Comment by bacca87** [comment]
il problema della lingua non è stato risolto, riapro.

**Comment by bacca87** [comment]
fixed
