### ISSUE TITLE
EDIT EA

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#70]
valutare se impedire di compilare le colonne dei giorni nei quali la NS non fa riferimento.
es. se vado via solo due giorni, ho la possibilità di inserire delle spese anche per un giorno in cui non ero via. 
se mai puoi far apparire un popup che ti dice che in quel giorno non ci sono riferimenti , così evito di imputare spese in modo sbagliato. poi se proprio lo voglio fare lo ignoro e vado avanti ....

**Comment by corradinia91** [comment]
Se però uno compila la NS quotidianamente ogni giorno ti trovi il popup di avviso, ed è abbastanza noioso. Sono l'unico che compila quasi quotidianamente le note spese?

**Comment by masierim** [comment]
no aspetta, forse mi sono spiegato male. ti faccio un (altro ) esempio.
io vado via giovedì e venerdì. 
nella NS metto una spesa di lunedì. evidentemente è un errore. 
quindi, nel momento di inserimento della spesa viene fuori un popup che ti dice "sei sicuro? guarda che non eri via lunedì, sei stato via giov e ven... pirla".

io non intendo che debba venire fuori un popup a cazzum... =)

**Comment by bacca87** [comment]
si puo fare, lo metto in lista

**Comment by corradinia91** [comment]
Siccome l'utente puo compilare prima la NS e poi il FDL il popup deve essere visualizzato quando si fa la compilazione.

**Comment by bacca87** [comment]
Secondo me non è un controllo da fare al volo sull'inserimento, perché uno potrebbe anche compilare prima la NS e poi le ore. 
Fin quando non vengono compilate le ore non possiamo sapere quali giorni ha lavorato e, se non le inserisci, ti darebbe errore su tutte le caselle.
Quello che farei io è di controllare tutto una volta sola sulla compilazione della nota spese. Quando fai compila comparirà un messaggio con scritto "Hai segnato dei rimborsi su dei giorni in cui non hai lavorato, vuoi continuare?"

**Comment by masierim** [comment]
ci stà....

**Comment by corradinia91** [comment]
Fatto
