### ISSUE TITLE
holiday - type day

### ISSUE THREAD

**Issue by masierim** [bacca87/great2#76]
i giorni di festa non devono essere inizializzati come giorni di lavoro.

al massimo come vacation day, poi se uno lavora quel determinato giorno lo cambierà ...

**Comment by bacca87** [comment]
Si hai ragione, adesso vediamo come risolvere.

**Comment by bacca87** [comment]
abbiamo deciso che la gestione delle ferie rimane la stessa, non segneremo le festività nazionali come giorni di ferie.
Però nel conteggio delle ferie godute nelle statistiche, nei totali sommeremo, in base allo stato corrente, la somma dei giorni festivi che non ricadono nel weekend.

## Note per gli sviluppatori:
Sito della libreria per la gestione delle ferie: https://github.com/tinohager/Nager.Date

#### Get all publicHolidays for a date range
```cs
var startDate = new DateTime(2016, 5, 1);
var endDate = new DateTime(2018, 5, 31);
var publicHolidays = DateSystem.GetPublicHoliday(CountryCode.DE, startDate, endDate);
foreach (var publicHoliday in publicHolidays)
{
	//publicHoliday...
}
```

#### Check if a date is a public holiday
```cs
var date = new DateTime(2017, 1, 1);
if (DateSystem.IsPublicHoliday(date, CountryCode.DE))
{
    Console.WriteLine("Is public holiday");
}
```

#### Check if a date is a weekend day
```cs
var date = new DateTime(2017, 1, 1);
if (DateSystem.IsWeekend(date, CountryCode.DE))
{
    Console.WriteLine("Is weekend");
}
```

controllare se queste info sono gia presenti come proprietà dei giorni, e usare quelle per un count fatto con linq.

**Comment by masierim** [comment]
cosa mi serve sapere che ho fatto di ferie natale, pasqua ecc.... ? 
io vorrei capire quanti giorni di ferie ho usato, non quanti giorni sono stato a casa......
si può fare una fetta a parte?

**Comment by bacca87** [comment]
Adesso è gia cosi, sei tu che hai aperto questo ticket dicendo di settare come vacation day i giorni di festa!

Ad ogni modo, i giorni di pasqua o natale sono giorni di ferie che ti vengono scalati dal tuo monte ore.
Sono ferie che consumi anche senza esplicita richiesta. Se a natale lavori, ti ritrovi con 1 giorni di ferie da usare perche non consumato.

Adesso se guardi i giorni di ferie conteggiati su great, non corrispondono con quelli della busta paga perche mancano le feste.

**Comment by masierim** [comment]
> Ad ogni modo, i giorni di pasqua o natale sono giorni di ferie che ti vengono scalati dal tuo monte ore.

non credo proprio,
tu hai un tot di giorni di ferie e permessi all'anno che non comprendo i giorni di festa...


> Adesso è già cosi, sei tu che hai aperto questo ticket dicendo di settare come vacation day i giorni di festa

e se li metti come special leave?


ad ogni modo.... 
si può avere una statistica che rispecchia i dati della busta paga?

**Comment by bacca87** [comment]
si hai ragione, mi sono informato meglio e i giorni di festa non sono conteggiati. Mi ha fregato il fatto che se una festa cade di domenica poi ti danno un giorno di ferie in piu.

A questo punto secondo me basta permettere all'utente di segnare le ferie solo nei giorni feriali che non sono una festa nazionale. Cosi facendo i conti dovrebbero tornare per quanto riguarda la busta.

**Comment by corradinia91** [comment]
dopo il pr #126 Durante la sincronizzazione con sharepoint i giorni sab e domenica non vengono più marcati come ferie sul calendario Great. L'utente può ancora falo manualmente. Necessario uno script per correggere i giorni già importati

**Comment by bacca87** [comment]
manca solo di bloccare l'utente se vuole segnare ferie in giorni festivi.
