### ISSUE TITLE
Completare gestione note spese

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#8]
Finire la pagina delle note spese

**Comment by bacca87** [comment]
Inserire autocompilazione note spese.
Tab salvataggio.

**Comment by bacca87** [comment]
limitare inserimento a massimo 15 tipi di spese per nota spese

**Comment by bacca87** [comment]
Rendere configurabile la valuta default per le note spese

**Comment by masierim** [comment]
aggiungere la data (sopra alla firma) in automatico

**Comment by bacca87** [comment]
aggiungere la possibilità di aggiungere note spese per differenti valute

**Comment by bacca87** [comment]
vedi #156

**Comment by corradinia91** [comment]
Aggiungere nella pagina NS (magari sotto alla tabella delle spese) il totale giornaliero. Torna utile per vedere se si ha sforato il budget

**Comment by bacca87** [comment]
Valutare come gestire le note spese in excel  #156.
In polonia usano una nota spese in excel totalmente diversa anche come formato e disposizione, in francia quella classica in excel, in america usano un app che si chiama Nexonia e in cile usano le notespese classiche in PDF come in italia.
