### ISSUE TITLE
Invio FDL corretti

### ISSUE THREAD

**Issue by corradinia91** [bacca87/great2#81]
Quando si invia per la seconda volta un FDL nell'oggetto della mail indicare che si tratta di un nuovo invio altrimenti HR non sa qual'è quello buono

**Comment by bacca87** [comment]
HR non è in grado di guardare la data di ricevimento nell'email? o pensa che viaggiamo nel tempo?

**Comment by corradinia91** [comment]
La seconda.

**Comment by bacca87** [comment]
beh noi non siamo micca degli assistenti sociali, se sono handicappati si fanno dare l'invalidità e stanno a casa. Figurati se bisogna fare del SW perche non sono in grado di ordinare le email per ultimo ricevuto.

**Comment by bacca87** [comment]
chiudo
