### ISSUE TITLE
Stato FDL secondo invio

### ISSUE THREAD

**Issue by corradinia91** [bacca87/great2#82]
Se si rimanda a sistema un fdl e il foglio precedente è stato accettato, bisogna attendere una nuova mail di conferma prima di marcare il foglio come accepted

**Comment by bacca87** [comment]
Questo potrebbe essere un problema... Bisogna capire come fare.

**Comment by corradinia91** [comment]
Ho messo un timestamp di ultimo invio, poi controllo la data di ricezione della mail e faccio il confronto
Anche per le NS

**Comment by bacca87** [comment]
si ci sta, la data però salvala quando effettivamente è stato inviato, non al semplice click del pulsante invia. Occhio che la stessa funzione di invio viene usata anche per gli invii a terzi, e in quel caso il timestamp va ignorato.
