### ISSUE TITLE
Compilazione FDL

### ISSUE THREAD

**Issue by corradinia91** [bacca87/great2#83]
Quando si ricompila un FDL bisogna sovrascrivere tutti i campi orario, anche quelli non utilizzati

**Comment by bacca87** [comment]
Ah non lo fa gia? allora bug!
Direi stessa cosa anche per le note spese...

**Comment by corradinia91** [comment]
No, ieri ho rimandato un fdl e me lo ha compilato a tenendo alcuni campi vecchi
