### ISSUE TITLE
Interfaccia noleggi auto

### ISSUE THREAD

**Issue by bacca87** [bacca87/great2#88]
Cose da modificare per rendere la pagina dei noleggi accettabile:

- [x] Ordinare i noleggi dal piu recente al piu vecchio (descending)
- [x] Aggiungere le colonne: durata del noleggio, km totali percorsi, locazione di partenza, locazione di arrivo
- [x] Disposizione delle colonne come segue: Targa, Marca, Modello, km percorsi, loc.partenza, loc. arrivo, durata, data inizio, data fine.
- [x] Autocompletamento marca, modello, locazione partenza, locazione arrivo.
- [x] Quando viene selezionato il textbox dei km, selezionare automaticamente il testo in maniera da non dover cancellare lo 0 per poi inserire i km.
- [x]  livello di benzina iniziale e finale settati di default al massimo, il 99,99% delle volte è cosi.
- [x] Ingrandire il campo note e metterlo su piu righe
- [x] Ingrandire tutti i campi in generale per renderlo piu visibile e per riempire tutto lo spazio vuoto inutile.
- [x] Le date di inizio e fine noleggio vanno settate di default a oggi, se no ogni volta che inserisco una data, devo partire dal 1970 e arrivare a oggi
- [x] Il datepicker dei filtri deve aprirsi con la data selezionata di oggi, non dall'anno della nascita di gesu cristo.
- [x] I filtri non devono essere case sensitive, se scrivo fiat o FiAt, mi deve tirare su tutte le FIAT!!!
- [x] Forzare la scrittura della targa all'interno della textbox tutto in MAIUSCOLO

**Comment by corradinia91** [comment]
Work in progress

**Comment by bacca87** [comment]
bisogna dedicare piu spazio per la tabella e meno per l'inserimento. Ora l'inserimento occupa un bordello di spazio per niente. Ridimensionare.

Quando parte great, e si passa nella pagina dei noleggi, nessun noleggio è selezionato e i dati a lato hanno come livello di benzina a 0 anzi che 8. tutto si sistema solo dopo che ho premuto il tasto new.

la colonna della durata visualizza anche valori periodici o con diverse cifre oltre la virgola. Approssimare i valori oppure usare una unità di misura dinamica.

**Comment by bacca87** [comment]
manca l'arrotondamento della durata

![2019-08-27 18_04_11-GREAT²](https://user-images.githubusercontent.com/6023494/63788355-9db5f080-c8f5-11e9-95c7-b69a822b1976.png)

**Comment by corradinia91** [comment]
PD
